services:
  nids:
    build:
      context: .
      dockerfile: Dockerfile
    image: nids-adv:latest
    container_name: nids-adv-dev

    # Environment variables
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"

    # Ports
    ports:
      - "8888:8888"

    working_dir: /workspace
    init: true
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
