name: nids-adv
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.13.12
  - numpy>=2.0 # Fixes the numpy._core error
  - scikit-learn==1.8.0 # Upgraded to support NumPy 2.x
  - pandas>=2.2 # Upgraded for compatibility
  - xgboost>=2.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - jupyter
  - pytest
  - pip
  - pytest-cov
  - pip:
      - tensorflow==2.21.0 # Upgraded for better performance and compatibility
      - keras==3.13.2
