"""
Retrain baseline models (RF, XGBoost, MLP + majority-voting ensemble)
on an adversarial training dataset from data/adversarial/. 

Validation uses the original split from data/splits/<dataset>.npz (unchanged).

Default mode - full adversarial data (all three attack families combined):
    python src/train_adversarial.py --dataset cicids2017
    python src/train_adversarial.py --all

Partial mode - trained on a single attack family only:
    python src/train_adversarial.py --dataset cicids2017 --attack a
    python src/train_adversarial.py --all --attack b

Partial mode reads from data/adversarial/adv_train_{stem}_attack_{a|b|c}_only.npz
(generated by src/gen_adversarial_partial.py) and saves models/results under a
distinct prefix so they never overwrite the fully-trained adversarial artifacts.

prefixes:
  default -> adv_{rf,xgb,mlp}_{dataset}.*   (same as before)
  --attack a -> adv_a_only_{rf,xgb,mlp}_{dataset}.*
  --attack b -> adv_b_only_{rf,xgb,mlp}_{dataset}.*
  --attack c -> adv_c_only_{rf,xgb,mlp}_{dataset}.*

Metrics JSON:
  default -> results/retrained_adversarial_metrics_{dataset}.json
  --attack a -> results/retrained_adversarial_attack_a_only_metrics_{dataset}.json
"""
import json
import argparse
from pathlib import Path
from scipy.stats import mode
from typing import Optional
import sys

import numpy as np
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix,
)
from sklearn.utils.class_weight import compute_class_weight
import xgboost as xgb

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

# Allow both:
# - python -m src.train_adversarial
# - python src/train_adversarial.py
if __package__ is None or __package__ == "":
    repo_root = Path(__file__).resolve().parents[1]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))

from src.dotenv_utils import get_env_int, get_env_str

RF_N_ESTIMATORS = get_env_int("RF_N_ESTIMATORS")
RF_RANDOM_STATE = get_env_int("RF_RANDOM_STATE")
RF_N_JOBS = get_env_int("RF_N_JOBS")
RF_CLASS_WEIGHT = get_env_str("RF_CLASS_WEIGHT")
XGB_RANDOM_STATE = get_env_int("XGB_RANDOM_STATE")
XGB_N_JOBS = get_env_int("XGB_N_JOBS")
MLP_HIDDEN_1 = get_env_int("MLP_HIDDEN_1")
MLP_HIDDEN_2 = get_env_int("MLP_HIDDEN_2")
MLP_HIDDEN_3 = get_env_int("MLP_HIDDEN_3")
MLP_OPTIMIZER = get_env_str("MLP_OPTIMIZER")
MLP_EARLYSTOP_PATIENCE = get_env_int("MLP_EARLYSTOP_PATIENCE")
MLP_EPOCHS = get_env_int("MLP_EPOCHS")
MLP_BATCH_SIZE = get_env_int("MLP_BATCH_SIZE")

# Directory Setup
SPLITS_DIR = Path("data/splits")
ADV_DIR = Path("data/adversarial")
ADV_SUMMARY_PATH = ADV_DIR / "adv_generation_summary.json"
# File stems after adv_train_ - must match src/gen_adversarial_dataset.py DATASET_NAME_MAP
ADV_TRAIN_STEM = {"cicids2017": "cicids", "nslkdd": "nslkdd", "unswnb15": "unswnb15"}

MODELS_DIR = Path("models")
RESULTS_DIR = Path("results")

MODELS_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

DATASETS = ["cicids2017", "nslkdd", "unswnb15"]


### Helpers ###

def _model_prefix(attack: Optional[str]) -> str:
    """Return the filename prefix for saved models and scalers."""
    if attack:
        return f"adv_{attack}_only"
    return "adv"


def _results_stem(attack: Optional[str]) -> str:
    """Return the results filename stem (without dataset suffix)."""
    if attack:
        return f"retrained_adversarial_attack_{attack}_only_metrics"
    return "retrained_adversarial_metrics"


### Data Loading ###

def load_split_stats():
    """Fetch metadata like row counts, label maps, and feature names."""
    path = SPLITS_DIR / "split_stats.json"
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return None


def get_label_map(dataset_name, split_stats):
    """Retrieve the mapping of integer labels to string class names."""
    if split_stats and dataset_name in split_stats:
        return {int(k): v for k, v in split_stats[dataset_name]["label_map"].items()}

    fallback_path = SPLITS_DIR / f"{dataset_name}_label_map.npy"
    if fallback_path.exists():
        return np.load(fallback_path, allow_pickle=True).item()

    raise FileNotFoundError(
        f"Could not find a label map for {dataset_name}. Make sure to run the preprocessor."
    )


def _resolve_adv_train_npz(dataset_name: str, attack: Optional[str] = None) -> Path:
    """
    Locate the adversarial training .npz file.

    - attack=None -> full adversarial data (gen_adversarial_dataset.py output)
    - attack='a' -> partial data for attack A (gen_adversarial_partial.py output)
    """
    stem = ADV_TRAIN_STEM.get(dataset_name)
    candidates: list[Path] = []

    if attack:
        # Partial dataset: generated by gen_adversarial_partial.py
        if stem:
            candidates.append(ADV_DIR / f"adv_train_{stem}_attack_{attack}_only.npz")
        # Fallback using the partial summary JSON
        partial_summary = ADV_DIR / f"adv_partial_generation_summary_{attack}.json"
        if partial_summary.exists():
            with open(partial_summary, encoding="utf-8") as f:
                summary = json.load(f)
            op = (summary.get(dataset_name) or {}).get("output_path")
            if op:
                candidates.append(Path(str(op).replace("\\", "/")))
    else:
        # Full adversarial dataset: generated by gen_adversarial_dataset.py
        if ADV_SUMMARY_PATH.exists():
            with open(ADV_SUMMARY_PATH, encoding="utf-8") as f:
                summary = json.load(f)
            op = (summary.get(dataset_name) or {}).get("output_path")
            if op:
                candidates.append(Path(str(op).replace("\\", "/")))
        if stem:
            candidates.append(ADV_DIR / f"adv_train_{stem}.npz")
        if dataset_name == "unswnb15":
            candidates.append(ADV_DIR / "adv_train_unsw_nb15.npz")

    for p in candidates:
        if p.is_file():
            return p

    tried = ", ".join(str(p) for p in candidates) if candidates else "(none)"
    gen_cmd = (
        f"python src/gen_adversarial_partial.py --attack {attack}"
        if attack
        else "python src/gen_adversarial_dataset.py"
    )
    raise FileNotFoundError(
        f"No adversarial training .npz found for {dataset_name} (attack={attack}). "
        f"Tried: {tried}. Run: {gen_cmd}"
    )


def load_adversarial_mixed_dataset(dataset_name, split_stats=None, attack=None):
    """
    Training: data/adversarial/adv_train_*.npz (70% stratified clean + generated adversarial).
    Validation: data/splits/<dataset>.npz (unchanged split).
    """
    adv_path = _resolve_adv_train_npz(dataset_name, attack)
    base_path = SPLITS_DIR / f"{dataset_name}.npz"

    if not base_path.exists():
        raise FileNotFoundError(
            f"Missing validation split for {dataset_name}: {base_path}"
        )

    adv_data = np.load(adv_path, allow_pickle=True)
    base_data = np.load(base_path, allow_pickle=True)

    if "X_train" not in adv_data.files or "y_train" not in adv_data.files:
        raise KeyError(f"{adv_path} must contain X_train and y_train")

    label_map = get_label_map(dataset_name, split_stats)

    return (
        adv_data["X_train"],
        adv_data["y_train"],
        base_data["X_val"],
        base_data["y_val"],
        label_map,
        adv_path,
    )


### Metrics ###

def compute_metrics(y_true, y_pred, label_map):
    """Calculates accuracy, per-class stats (Precision/Recall/F1), and a confusion matrix."""
    labels = list(range(len(label_map)))
    target_names = [label_map[i] for i in labels]

    acc = float(accuracy_score(y_true, y_pred))
    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, labels=labels, zero_division=0
    )
    cm = confusion_matrix(y_true, y_pred, labels=labels)

    per_class = {
        name: {"precision": float(p), "recall": float(r), "f1": float(f)}
        for name, p, r, f in zip(target_names, prec, rec, f1)
    }

    return {
        "accuracy": acc,
        "per_class": per_class,
        "confusion_matrix": cm.tolist(),
        "confusion_matrix_labels": target_names,
    }


### Model Trainers ###

def train_rf(X_train, y_train, X_val, y_val, label_map, dataset_name, prefix: str):
    """Trains and saves a balanced Random Forest classifier."""
    model = RandomForestClassifier(
        n_estimators=RF_N_ESTIMATORS,
        random_state=RF_RANDOM_STATE,
        n_jobs=RF_N_JOBS,
        class_weight=RF_CLASS_WEIGHT,
    )
    model.fit(X_train, y_train)
    joblib.dump(model, MODELS_DIR / f"{prefix}_rf_{dataset_name}.pkl")
    return model, compute_metrics(y_val, model.predict(X_val), label_map)


def train_xgb(X_train, y_train, X_val, y_val, label_map, dataset_name, prefix: str):
    """Trains and saves an XGBoost classifier with sample weights for class imbalance."""
    cw = compute_class_weight("balanced", classes=np.unique(y_train), y=y_train)
    sample_weights = np.array([cw[c] for c in y_train])

    model = xgb.XGBClassifier(
        random_state=XGB_RANDOM_STATE,
        n_jobs=XGB_N_JOBS,
    )
    model.fit(X_train, y_train, sample_weight=sample_weights)
    joblib.dump(model, MODELS_DIR / f"{prefix}_xgb_{dataset_name}.pkl")
    return model, compute_metrics(y_val, model.predict(X_val), label_map)


def train_mlp(X_train, y_train, X_val, y_val, label_map, dataset_name, prefix: str):
    """
    Trains and saves a 3-layer MLP with StandardScaler preprocessing.
    Uses EarlyStopping to avoid overfitting on rare classes.
    """
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_val_scaled = scaler.transform(X_val)
    joblib.dump(scaler, MODELS_DIR / f"{prefix}_scaler_{dataset_name}.pkl")

    cw = compute_class_weight("balanced", classes=np.unique(y_train), y=y_train)
    class_weights = dict(enumerate(cw))

    model = Sequential([
        Dense(MLP_HIDDEN_1, activation="relu", input_shape=(X_train_scaled.shape[1],)),
        Dense(MLP_HIDDEN_2, activation="relu"),
        Dense(MLP_HIDDEN_3, activation="relu"),
        Dense(len(label_map), activation="softmax"),
    ])
    model.compile(
        optimizer=MLP_OPTIMIZER,
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    early_stop = EarlyStopping(
        monitor="val_accuracy",
        patience=MLP_EARLYSTOP_PATIENCE,
        restore_best_weights=True,
        verbose=1,
    )
    model.fit(
        X_train_scaled, y_train,
        epochs=MLP_EPOCHS,
        batch_size=MLP_BATCH_SIZE,
        class_weight=class_weights,
        validation_data=(X_val_scaled, y_val),
        callbacks=[early_stop],
        verbose=1,
    )
    model.save(MODELS_DIR / f"{prefix}_mlp_{dataset_name}.h5", save_format="h5")

    y_pred = np.argmax(model.predict(X_val_scaled, verbose=0), axis=1)
    return model, compute_metrics(y_val, y_pred, label_map)


### Ensemble ###

def majority_vote(preds_list):
    """Vectorized majority voting across model predictions using SciPy."""
    preds = np.stack(preds_list, axis=1)
    return mode(preds, axis=1, keepdims=False).mode


### Pipeline ###

def run_one_dataset(dataset_name, split_stats, attack: Optional[str] = None):
    """Executes the adversarial training pipeline for one dataset."""
    prefix = _model_prefix(attack)
    mode_label = f"attack {attack.upper()} only" if attack else "all attacks"

    print(f"\n{'='*60}")
    print(f"Adversarial Training - {dataset_name.upper()} ({mode_label})")

    X_train, y_train, X_val, y_val, label_map, adv_train_path = load_adversarial_mixed_dataset(
        dataset_name, split_stats, attack=attack
    )
    print(f"  Train file: {adv_train_path}")
    print(
        f"  Data: {X_train.shape[0]:,} train samples | "
        f"{X_val.shape[0]:,} val samples | {len(label_map)} classes"
    )

    all_metrics = {}
    preds_for_vote = []

    # 1. Random Forest
    print("\nTraining Random Forest...")
    rf_model, rf_metrics = train_rf(
        X_train, y_train, X_val, y_val, label_map, dataset_name, prefix
    )
    all_metrics["random_forest"] = rf_metrics
    preds_for_vote.append(rf_model.predict(X_val))
    print(f"   RF Validation Accuracy: {rf_metrics['accuracy']:.4f}")

    # 2. XGBoost
    print("\nTraining XGBoost...")
    xgb_model, xgb_metrics = train_xgb(
        X_train, y_train, X_val, y_val, label_map, dataset_name, prefix
    )
    all_metrics["xgboost"] = xgb_metrics
    preds_for_vote.append(xgb_model.predict(X_val))
    print(f"   XGB Validation Accuracy: {xgb_metrics['accuracy']:.4f}")

    # 3. MLP
    print("\nTraining 3-Layer MLP...")
    mlp_model, mlp_metrics = train_mlp(
        X_train, y_train, X_val, y_val, label_map, dataset_name, prefix
    )
    all_metrics["mlp"] = mlp_metrics
    scaler = joblib.load(MODELS_DIR / f"{prefix}_scaler_{dataset_name}.pkl")
    preds_for_vote.append(
        np.argmax(mlp_model.predict(scaler.transform(X_val), verbose=0), axis=1)
    )
    print(f"   MLP Validation Accuracy: {mlp_metrics['accuracy']:.4f}")

    # 4. Ensemble (RF + XGBoost + MLP majority vote)
    print("\nCalculating Majority Vote Ensemble...")
    ensemble_pred = majority_vote(preds_for_vote)
    all_metrics["majority_voting"] = compute_metrics(y_val, ensemble_pred, label_map)
    print(f"   Ensemble Validation Accuracy: {all_metrics['majority_voting']['accuracy']:.4f}")

    return all_metrics


### CLI ###

def main():
    parser = argparse.ArgumentParser(
        description="Retrain NIDS models on adversarially mixed data to improve robustness."
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--dataset", type=str, choices=DATASETS,
        help="Train and evaluate on a specific dataset.",
    )
    group.add_argument(
        "--all", action="store_true",
        help="Run the pipeline on all three datasets.",
    )
    parser.add_argument(
        "--attack", type=str, choices=["a", "b", "c"], default=None,
        help=(
            "Use partial adversarial data trained on a single attack family "
            "(a=feature obfuscation, b=behavioral mimicry, c=protocol exploitation). "
            "Omit to use the full mixed adversarial dataset (default behaviour)."
        ),
    )

    args = parser.parse_args()
    split_stats = load_split_stats()

    if split_stats:
        print("Loaded split_stats.json successfully.")
    else:
        print("split_stats.json not found. Falling back to .npy label maps.")

    datasets_to_run = DATASETS if args.all else [args.dataset]
    results_stem = _results_stem(args.attack)
    combined_metrics = {}

    for dataset_name in datasets_to_run:
        metrics = run_one_dataset(dataset_name, split_stats, attack=args.attack)

        out_path = RESULTS_DIR / f"{results_stem}_{dataset_name}.json"
        with open(out_path, "w") as f:
            json.dump(metrics, f, indent=2)
        print(f"\nSaved metrics to {out_path}")

        combined_metrics[dataset_name] = metrics

    if args.all:
        summary_path = RESULTS_DIR / f"{results_stem}.json"
        with open(summary_path, "w") as f:
            json.dump(combined_metrics, f, indent=2)
        print(f"\nCombined metrics saved to {summary_path}")


if __name__ == "__main__":
    main()
